<h1>Deletar</h1>

<?php
 // module/Album/view/album/album/delete.phtml:

 $title = 'Deletar Disco';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <p>Tem certeza que deseja apagar o Disco?
     '<?php echo $this->escapeHtml($disco->disco); ?>' by
     '<?php echo $this->escapeHtml($disco->cantor); ?>'?
 </p>
 <?php
 $url = $this->url('album', array(
     'action' => 'delete',
     'id'     => $this->id,
 ));
 ?>
 <form action="<?php echo $url; ?>" method="post">
 <div>
     <input type="hidden" name="id" value="<?php echo (int) $disco->id; ?>" />
     <input type="submit" name="del" value="Sim" />
     <input type="submit" name="del" value="Não" />
 </div>
 </form>