<h1>Edit</h1>
<?php



$form->setAttribute( 'action', $this->url(
        'album', array(
            'action' => 'edit',
            'id'    => $this->id,
            )
        ));

$form->prepare();

echo $this->form()->openTag( $form );
echo $this->formHidden( $form->get('id') );
echo $this->formRow( $form->get('disco') );
echo $this->formRow( $form->get('cantor') );
echo $this->formSubmit( $form->get('submit') );
echo $this->form()->closeTag();

